

apiVersion: v1
kind: Service
metadata:
  name: fab-upgrade
  namespace: infra
  labels:
    app: fab-upgrade
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: fab-upgrade


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fab-upgrade
  namespace: infra
  labels:
    app: fab-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fab-upgrade
  template:
    metadata:
      name: fab-upgrade
      labels:
        app: fab-upgrade
    spec:
      containers:
        - name: fab-upgrade
          image: ai.tencentmusic.com/tme-public/fab-upgrade:2020.09.01.0
          imagePullPolicy: Always  # IfNotPresent
          command: ["python","server.py"]    # 如果修改了entrypoint要使用命令执行
#          command: ["sleep","300000"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP