
# 模型训练
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-user-workspace
  labels:
    pipeline-pvname: pipeline-kubeflow-user-workspace
spec:
#  storageClassName: pipeline
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      pipeline-pvname: pipeline-kubeflow-user-workspace

---

# 模型训练
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-kubeflow-user-workspace
  labels:
    jupyter-pvname: jupyter-kubeflow-user-workspace
spec:
#  storageClassName: pipeline
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      jupyter-pvname: jupyter-kubeflow-user-workspace
