
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: infra
  labels:
    app: mysql
data:
  mysqld.cnf: |-
    [mysqld]
    skip-name-resolve
    #log-bin=mysql-bin #添加这一行就ok
    #binlog-format=ROW #选择row模式
    #server_id=1 #配置mysql replaction需要定义，不能和canal的slaveId重复
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    #log-error      = /var/log/mysql/error.log
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    bind-address    = 0.0.0.0
    max_connections = 1000
    innodb_buffer_pool_size=2G
    explicit_defaults_for_timestamp = 1
    character_set_server=utf8
    init_connect='SET NAMES utf8'
    skip-grant-tables

  init.sql: |-

    CREATE DATABASE IF NOT EXISTS pipeline DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

    CREATE DATABASE IF NOT EXISTS argo DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;



---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv
  labels:
    infra-pvname: infra-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/infra/mysql
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: infra-mysql-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      infra-pvname: infra-mysql-pv


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: infra
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: remove-lost-found
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      imagePullSecrets:
      - name: hubsecret
      containers:
        - name: mysql
          image: mysql:5.7    # mysql:5.7   # mysql:8.0.26
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mysql-configmap
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
              readOnly: False
            - name: mysql-configmap
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: False
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_ROOT_PASSWORD
            value: admin
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: infra-mysql-pvc
        - name: mysql-configmap
          configMap:
            name: mysql-configmap
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql-service
  namespace: infra
spec:
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
  selector:
    app: mysql

